language: python

addons:
    apt:
        sources:
            # add PPAs with more up-to-date toolchains
            - ubuntu-toolchain-r-test
        packages:
            # install toolchains
            - gfortran-4.8
            - gcc-5
            - g++-5
            - libopenblas-dev
            - liblapack-dev
            - libhdf5-serial-dev

matrix:
    include:
        - python: "2.7"
          env: COMPILER=g++-5
        - python: "3.5"
          env: COMPILER=g++-5

before_install:
    - pip install numpy matplotlib h5py

script:
    - ./bootstrap
    - mkdir BUILD
    - cd BUILD
    - ../configure CXX=$COMPILER F2PY=f2py FC=gfortran-4.8
    - make install
    - source activate-top.sh
    - make test
